version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  pre_build:
    commands:
      - node --version
      - npm --version
      - aws --version
  
  build:
    commands:
      - cd dev-portal
      - npm install
      - cd ..
      - npm install --only=dev
      
      - npm test
      #- aws cloudformation validate-template --template-body file://cloudformation/template.yaml
      
  post_build:
    commands:
      - aws cloudformation package --template ./cloudformation/template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  files:
    - template-export.yml
    - env-vars/prod.json
  discard-paths: yes